version: '3.7'
services:
  hyperplan-server:
    image: hyperplan/server:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - hyperplan
    environment:
      - APP_SECRET=replacewithrandomsecret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
  postgres:
    image: postgres
    networks:
      - hyperplan
    environment:
      - POSTGRESQL_PASSWORD=postgres
networks:
  hyperplan:
    name: "hyperplan"
    driver: "bridge"